id: P010792
initial_creation_type: ocr
source_metadata:
  id: bdr:W19830
  title: དྷི་ཚ་དགོན་པའི་གདན་རབས
  author: ''
  volumes:
    c208d9d0b5aa4b36b3af399dd97c11c9:
      image_group_id: I4215
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
