id: P010792
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-20 10:24:44.072494
source_metadata:
  id: bdr:W19830
  title: དྷི་ཚ་དགོན་པའི་གདན་རབས
  author: ''
  volumes:
    c208d9d0b5aa4b36b3af399dd97c11c9:
      image_group_id: I4215
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
